services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - CACHE_BUST=${CACHE_BUST}
    ports:
      - "80:80"
