version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:80"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
