name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t backend ./backend

      - name: Build frontend image
        run: docker build -t frontend ./frontend

      - name: Run backend tests (optional)
        run: |
          cd backend
          dotnet test || true   # Avoid breaking pipeline if tests aren't ready

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 Host to Known Hosts
        run: |
          ssh-keyscan -H 3.84.112.14 >> ~/.ssh/known_hosts

      - name: Deploy to EC2 Instance
        run: |
          ssh ubuntu@3.84.112.14 << 'EOF'
            cd ~/hello-world-deployment
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF
